version: '2'
services:
    hazelcastpoc-app:
        image: hazelcastpoc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hazelcastpoc-mysql:3306/hazelcastpoc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    hazelcastpoc-mysql:
        extends:
            file: mysql.yml
            service: hazelcastpoc-mysql
